### ISSUE TITLE
Where to configure the mod?

### ISSUE THREAD

**Issue by ThatsNotAName** [natis1/combomod#1]
So the README says "Fully configurable" but I'm not entirely sure where that config is located at? After installing the mod with Gradow's mod manager I don't see anything in terms of config... Also I tried looking at the raw files and I can't understand most of it, but that's mostly because I know next to nothing about coding.

How do you configure the settings? It doesn't really tell you how in the README

**Comment by natis1** [comment]
Hi. I'm sorry that this isn't well documented. All mod configuration files are located in the save game folder. This folder location is given on the pc game wiki for your OS: See this link https://www.pcgamingwiki.com/wiki/Hollow_Knight
